<a href="https://colab.research.google.com/github/Manivardhan2250/SML_2303A52250_Batch_43/blob/main/SML_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Load the data
df = pd.read_csv('/content/train.csv')
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [36]:
# Define the target variable and features
target = 'battery_power'  # Replace with your actual target column name
features = [col for col in df.columns if col != target]

X = df[features]  # Features
y = df[target]    # Target variable
print(X)
print(y)

      blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  mobile_wt  \
0        0          2.2         0   1       0           7    0.6        188
1        1          0.5         1   0       1          53    0.7        136
2        1          0.5         1   2       1          41    0.9        145
3        1          2.5         0   0       0          10    0.8        131
4        1          1.2         0  13       1          44    0.6        141
...    ...          ...       ...  ..     ...         ...    ...        ...
1995     1          0.5         1   0       1           2    0.8        106
1996     1          2.6         1   0       0          39    0.2        187
1997     0          0.9         1   1       1          36    0.7        108
1998     0          0.9         0   4       1          46    0.1        145
1999     1          2.0         1   5       1          45    0.9        168

      n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  three_g  \
0           2   2         20       756  2549     9     7         19        0
1           3   6        905      1988  2631    17     3          7        1
2           5   6       1263      1716  2603    11     2          9        1
3           6   9       1216      1786  2769    16     8         11        1
4           2  14       1208      1212  1411     8     2         15        1
...       ...  ..        ...       ...   ...   ...   ...        ...      ...
1995        6  14       1222      1890   668    13     4         19        1
1996        4   3        915      1965  2032    11    10         16        1
1997        8   3        868      1632  3057     9     1          5        1
1998        5   5        336       670   869    18    10         19        1
1999        6  16        483       754  3919    19     4          2        1

      touch_screen  wifi  price_range
0                0     1            1
1                1     0            2
2                1     0            2
3                0     0            2
4                1     0            1
...            ...   ...          ...
1995             1     0            0
1996             1     1            2
1997             1     0            3
1998             1     1            0
1999             1     1            3

[2000 rows x 20 columns]
0        842
1       1021
2        563
3        615
4       1821
        ...
1995     794
1996    1965
1997    1911
1998    1512
1999     510
Name: battery_power, Length: 2000, dtype: int64

In [37]:
# Initialize the scaler
scaler = MinMaxScaler()

# Fit and transform the features
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[0.         0.68       0.         ... 0.         1.         0.33333333]
 [1.         0.         1.         ... 1.         0.         0.66666667]
 [1.         0.         1.         ... 1.         0.         0.66666667]
 ...
 [0.         0.16       1.         ... 1.         0.         1.        ]
 [0.         0.16       0.         ... 1.         1.         0.        ]
 [1.         0.6        1.         ... 1.         1.         1.        ]]

In [38]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)
print(X_train)
print(y_train)

[[0.         0.         1.         ... 1.         1.         0.33333333]
 [1.         0.68       0.         ... 1.         1.         0.66666667]
 [0.         0.16       1.         ... 0.         1.         0.        ]
 ...
 [1.         0.         0.         ... 0.         1.         0.66666667]
 [0.         0.16       1.         ... 1.         1.         1.        ]
 [1.         0.04       1.         ... 0.         0.         0.33333333]]
968     1923
240      633
819     1236
692      781
420     1456
        ...
1130    1975
1294     589
860     1829
1459    1927
1126     635
Name: battery_power, Length: 1600, dtype: int64